# Generated by Django 6.0.4 on 2026-04-11 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Locutor')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='locutores/', verbose_name='Foto do Locutor')),
            ],
            options={
                'verbose_name': 'Locutor',
                'verbose_name_plural': 'Locutores',
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da Promoção')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem_banner', models.ImageField(upload_to='promocoes/', verbose_name='Banner da Promoção')),
                ('link_whatsapp', models.URLField(blank=True, help_text='Ex: https://wa.me/55999999999', null=True, verbose_name='Link de Redirecionamento (WhatsApp)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Promoção Ativa?')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Programa')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Dia da Semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('imagem_banner', models.ImageField(blank=True, null=True, upload_to='programas/banners/', verbose_name='Banner do Programa')),
                ('locutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='centralfm.locutor')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['dia_semana', 'horario_inicio'],
            },
        ),
    ]
