# Generated by Django 5.2.8 on 2026-04-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralfm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='locutor',
        ),
        migrations.DeleteModel(
            name='Locutor',
        ),
        migrations.DeleteModel(
            name='Programa',
        ),
    ]
