# Generated by Django 5.2.8 on 2026-04-12 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralfm', '0003_locutor_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='emoji',
            field=models.CharField(blank=True, help_text='Ex: 🍕 ou 🏆', max_length=10, null=True, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='locutor',
            field=models.ForeignKey(blank=True, help_text='Quem está apresentando este programa?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='centralfm.locutor'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='imagem_banner',
            field=models.ImageField(blank=True, null=True, upload_to='promocoes/', verbose_name='Banner da Promoção'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='link_whatsapp',
            field=models.URLField(blank=True, help_text='Ex: https://wa.me/5534996491118?text=Quero+Participar', null=True, verbose_name='Link de Redirecionamento (WhatsApp)'),
        ),
        migrations.CreateModel(
            name='Ganhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Ganhador')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('foto', models.ImageField(help_text='Importante: Use fotos no formato VERTICAL (9:16) para melhor visualização estilo Stories.', upload_to='ganhadores/', verbose_name='Foto do Ganhador')),
                ('data_inicio_semana', models.DateField(verbose_name='Início da Semana')),
                ('data_fim_semana', models.DateField(verbose_name='Fim da Semana')),
                ('ativo', models.BooleanField(default=True, verbose_name='Exibir no Site?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('promocao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganhadores', to='centralfm.promocao', verbose_name='Promoção Associada')),
            ],
            options={
                'verbose_name': 'Ganhador',
                'verbose_name_plural': 'Ganhadores',
                'ordering': ['-data_inicio_semana', '-criado_em'],
            },
        ),
    ]
