# Generated by Django 5.2.8 on 2026-04-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralfm', '0004_promocao_emoji_alter_programa_locutor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ganhador',
            name='cidade',
        ),
    ]
