# Generated by Django 5.2.8 on 2026-04-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralfm', '0005_remove_ganhador_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='emoji',
        ),
    ]
