# Generated by Django 6.0.4 on 2026-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralfm', '0006_remove_promocao_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganhador',
            name='foto',
            field=models.ImageField(help_text='Importante: Use fotos no formato 4:5 (Instagram Post) para melhor visualização.', upload_to='ganhadores/', verbose_name='Foto do Ganhador'),
        ),
    ]
