# Generated by Django 5.2.8 on 2026-05-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralfm', '0007_alter_ganhador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='locutor',
            name='gif_animado',
            field=models.FileField(blank=True, help_text='Se preenchido, substitui a foto estática por um GIF animado. Use .gif ou .webp animado.', null=True, upload_to='locutores/gifs/', verbose_name='GIF Animado (opcional)'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='link_whatsapp',
            field=models.URLField(blank=True, help_text='Deixe em branco para gerar automaticamente a partir do título.', null=True, verbose_name='Link WhatsApp (opcional)'),
        ),
    ]
