# Generated by Django 5.2.8 on 2026-05-03 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralfm', '0008_add_gif_animado_locutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='locutor_substituto',
            field=models.ForeignKey(blank=True, help_text='Selecione um locutor para substituir temporariamente o titular neste programa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_como_substituto', to='centralfm.locutor', verbose_name='Locutor Substituto'),
        ),
    ]
