# Generated by Django 5.2.8 on 2026-05-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralfm', '0009_programa_locutor_substituto'),
    ]

    operations = [
        migrations.AddField(
            model_name='locutor',
            name='bio',
            field=models.TextField(blank=True, help_text='Uma frase curta sobre o locutor ou seu bordão.', null=True, verbose_name='Biografia (Curta)'),
        ),
        migrations.AddField(
            model_name='locutor',
            name='instagram',
            field=models.URLField(blank=True, help_text='Link completo para o perfil do Instagram.', null=True, verbose_name='Link do Instagram'),
        ),
        migrations.AddField(
            model_name='locutor',
            name='mostrar_na_equipe',
            field=models.BooleanField(default=True, verbose_name='Mostrar na seção Nossa Equipe?'),
        ),
    ]
