# Generated by Django 5.2.8 on 2026-05-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralfm', '0010_locutor_bio_locutor_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locutor',
            name='mostrar_na_equipe',
        ),
    ]
