# Generated by Django 5.2.8 on 2026-06-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralfm', '0011_remove_locutor_mostrar_na_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Opcional. Se preenchido, a promoção sairá do carrossel automaticamente após esta data.', null=True, verbose_name='Data de Encerramento'),
        ),
    ]
